# Generated by Django 5.0 on 2023-12-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_delete_entregable_delete_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='valoracion',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(max_length=100),
        ),
    ]
